[package]
name = "ws_check"
description = "Type, trust-label, effect and budget checking for Wardscript."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
la-arena.workspace = true
ws_syntax.workspace = true
ws_resolve.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
