//! WIR to Python: one readable `.py` module per Wardscript module, plus a `.pyi` stub.
//! Generated code imports the `wardscript` runtime package as `_rt`.
//!
//! Records become frozen dataclasses. Enums whose variants have no fields become
//! `enum.Enum`s; others become a base class with one frozen dataclass per variant.

mod body;
mod names;

use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::PathBuf;

use ward_ir::{Enum, Module, ModuleId, Program, Record};

use crate::body::FnGen;
use crate::names::{Scope, type_var};

pub struct OutputFile {
    /// Relative to the output directory: `support/tickets.py`.
    pub path: PathBuf,
    pub contents: String,
}

#[derive(Clone, Copy, Debug, Default)]
pub struct Options {
    /// Functions become `async def`s, and models, approvers and tools are awaited.
    pub asyncio: bool,
    /// Also generate the `test` blocks, for `ward test`.
    pub tests: bool,
}

pub fn generate(program: &Program) -> Vec<OutputFile> {
    generate_with(program, Options::default())
}

pub fn generate_with(program: &Program, options: Options) -> Vec<OutputFile> {
    let mut files = Vec::new();
    for (i, module) in program.modules.iter().enumerate() {
        let id = ModuleId(i as u32);
        let base: PathBuf = module.name.split('.').collect();
        files.push(OutputFile {
            path: base.with_extension("py"),
            contents: python(program, id, module, options),
        });
        files.push(OutputFile {
            path: base.with_extension("pyi"),
            contents: stub(program, id, module, options),
        });
    }
    files
}

fn header(module: &Module) -> String {
    let file = std::path::Path::new(&module.path)
        .file_name()
        .map_or_else(|| module.path.clone(), |f| f.to_string_lossy().into_owned());
    format!("# Generated by `ward build` from {file}. Do not edit.\n")
}

/// Python names defined at the top level of the generated module.
fn top_level_names(program: &Program, module: &Module) -> HashSet<String> {
    let mut out = HashSet::new();
    for r in &module.records {
        out.insert(names::ident(&r.name));
    }
    for e in &module.enums {
        out.insert(names::ident(&e.name));
        for v in &e.variants {
            out.insert(names::variant_class(&e.name, &v.name));
        }
    }
    for c in &module.classes {
        out.insert(names::ident(&c.name));
    }
    for f in module.fns.iter().filter(|f| f.method.is_none()) {
        out.insert(names::ident(&f.name));
    }
    for r in &module.refinements {
        out.insert(r.name.clone());
    }
    for t in &module.tests {
        out.insert(t.func.name.clone());
    }
    for m in &program.modules {
        out.insert(names::module_alias(&m.name));
    }
    out
}

fn def(options: Options) -> &'static str {
    if options.asyncio { "async def" } else { "def" }
}

fn python(program: &Program, id: ModuleId, module: &Module, options: Options) -> String {
    let mut scope = Scope::new(program, Some(id));
    let mut body = String::new();

    for r in &module.records {
        record_class(&mut body, &mut scope, r, false);
    }
    for e in &module.enums {
        enum_classes(&mut body, &mut scope, e, false);
    }
    let top = top_level_names(program, module);
    for c in &module.classes {
        class(&mut body, &mut scope, &top, module, c, options, false);
    }
    for f in module.fns.iter().filter(|f| f.method.is_none()) {
        emit_fn(
            &mut body,
            &mut scope,
            &top,
            f,
            options,
            "",
            &names::ident(&f.name),
            &f.name,
        );
    }

    // Tests: each is its own run in the audit trace; `__ward_tests__` lists them.
    let mut tests = Vec::new();
    if options.tests {
        for t in &module.tests {
            let f = &t.func;
            let mut g = FnGen::new(f, &mut scope, &top);
            g.asyncio = options.asyncio;
            g.body();
            let _ = writeln!(body, "\n\n{} {}() -> None:", def(options), f.name);
            let _ = writeln!(
                body,
                "    with _rt.call({}, []):",
                names::string(&format!("test {}", t.name))
            );
            for line in g.lines {
                let _ = writeln!(body, "    {line}");
            }
            tests.push(format!(
                "    ({}, {}, {}),",
                names::string(&t.name),
                names::string(&t.site.to_string()),
                f.name
            ));
        }
    }

    // Refinements: plain functions of `it`, outside the audit trace.
    for r in &module.refinements {
        let f = &r.func;
        let mut g = FnGen::new(f, &mut scope, &top);
        g.body();
        let param = g.local(f.params[0]).to_owned();
        let _ = writeln!(body, "\n\ndef {}({param}) -> bool:", r.name);
        for line in g.lines {
            let _ = writeln!(body, "{line}");
        }
    }

    // Descriptions for the runtime, after every class exists.
    let mut registry = String::new();
    for r in &module.records {
        let name = names::ident(&r.name);
        let fields: Vec<String> = r
            .fields
            .iter()
            .map(|f| {
                format!(
                    "    ({}, {}, {}),",
                    names::string(&f.name),
                    names::string(&names::attr(&f.name)),
                    scope.descriptor(&f.ty)
                )
            })
            .collect();
        let _ = writeln!(
            registry,
            "_rt.record({name}, {}, lambda: [{}])",
            names::string(&r.name),
            bracketed(&fields)
        );
    }
    for e in &module.enums {
        let name = names::ident(&e.name);
        let variants: Vec<String> = e
            .variants
            .iter()
            .map(|v| {
                let fields: Vec<String> = v.fields.iter().map(|t| scope.descriptor(t)).collect();
                format!(
                    "    ({}, {name}.{}, [{}]),",
                    names::string(&v.name),
                    names::attr(&v.name),
                    fields.join(", ")
                )
            })
            .collect();
        let _ = writeln!(
            registry,
            "_rt.enum({name}, {}, lambda: [{}])",
            names::string(&e.name),
            bracketed(&variants)
        );
    }

    let mut out = header(module);
    out.push_str("from __future__ import annotations\n\n");
    let mut imports = Vec::new();
    if !module.records.is_empty() || module.enums.iter().any(|e| !e.is_unit_only()) {
        imports.push("import dataclasses as _dc".to_owned());
    }
    if module.enums.iter().any(Enum::is_unit_only) {
        imports.push("import enum as _enum".to_owned());
    }
    if scope.uses_typing {
        imports.push("import typing as _typing".to_owned());
    }
    imports.sort();
    for line in &imports {
        let _ = writeln!(out, "{line}");
    }
    if !imports.is_empty() {
        out.push('\n');
    }
    for line in scope.import_lines() {
        let _ = writeln!(out, "{line}");
    }
    out.push_str("from wardscript import _rt\n");

    let exported: Vec<String> = module
        .records
        .iter()
        .filter(|r| r.is_pub)
        .map(|r| &r.name)
        .chain(module.enums.iter().filter(|e| e.is_pub).map(|e| &e.name))
        .chain(module.classes.iter().filter(|c| c.is_pub).map(|c| &c.name))
        .chain(
            module
                .fns
                .iter()
                .filter(|f| f.is_pub && f.method.is_none())
                .map(|f| &f.name),
        )
        .map(|n| format!("    {},", names::string(&names::ident(n))))
        .collect();
    let _ = writeln!(out, "\n__all__ = [{}]", bracketed(&exported));
    out.push_str(&body);
    if options.tests {
        let _ = writeln!(registry, "__ward_tests__ = [{}]", bracketed(&tests));
    }
    if !registry.is_empty() {
        out.push_str("\n\n");
        out.push_str(&registry);
    }
    out
}

/// A function or method with its audit-trace run and budget. `indent` is the class
/// body's, for a method.
#[allow(clippy::too_many_arguments)]
fn emit_fn(
    body: &mut String,
    scope: &mut Scope,
    top: &HashSet<String>,
    f: &ward_ir::Fn,
    options: Options,
    indent: &str,
    py_name: &str,
    trace_name: &str,
) {
    let param_names: Vec<String> = {
        let g = FnGen::new(f, scope, top);
        f.params.iter().map(|&p| g.local(p).to_owned()).collect()
    };
    let is_method = f.method.is_some();
    let params: Vec<String> = param_names
        .iter()
        .zip(&f.params)
        .zip(&f.trusted)
        .enumerate()
        .map(|(i, ((name, &p), &trusted))| {
            if is_method && i == 0 {
                return name.clone();
            }
            let ann = scope.annotation(&f.locals[p].ty, &f.generics);
            if trusted {
                format!("{name}: _rt.Trusted[{ann}]")
            } else {
                format!("{name}: {ann}")
            }
        })
        .collect();
    let ret = scope.annotation(&f.ret, &f.generics);
    let mut g = FnGen::new(f, scope, top);
    g.asyncio = options.asyncio;
    g.body();
    let _ = writeln!(
        body,
        "\n{}{indent}{} {py_name}({}) -> {ret}:",
        if indent.is_empty() { "\n" } else { "" },
        def(options),
        params.join(", ")
    );
    // The outermost call is a run in the audit trace.
    let args: Vec<String> = param_names
        .iter()
        .zip(&f.params)
        .skip(usize::from(is_method))
        .map(|(n, &p)| format!("({}, {n})", names::string(&f.locals[p].name)))
        .collect();
    let mut contexts = vec![format!(
        "_rt.call({}, [{}])",
        names::string(trace_name),
        args.join(", ")
    )];
    if !f.budget.is_empty() {
        let limits: Vec<String> = f
            .budget
            .iter()
            .map(|(k, v)| match v {
                ward_ir::BudgetValue::Int(n) => format!("{k}={n}"),
                ward_ir::BudgetValue::Float(x) => format!("{k}={x:?}"),
            })
            .collect();
        contexts.push(format!(
            "_rt.budget({}, {})",
            names::string(trace_name),
            limits.join(", ")
        ));
    }
    let _ = writeln!(body, "{indent}    with {}:", contexts.join(", "));
    for line in g.lines {
        let _ = writeln!(body, "{indent}    {line}");
    }
}

/// A class: field annotations, then its methods. In async code a constructor can't
/// await, so objects are made by `await Class._new(...)`, which runs `_init`.
fn class(
    out: &mut String,
    scope: &mut Scope,
    top: &HashSet<String>,
    module: &Module,
    c: &ward_ir::Class,
    options: Options,
    stub: bool,
) {
    let name = names::ident(&c.name);
    let methods: Vec<&ward_ir::Fn> = c
        .methods
        .iter()
        .filter_map(|&d| module.fns.iter().find(|f| f.def == d))
        .collect();
    // Interfaces are protocols: classes match them by their methods, not by inheriting.
    if c.kind == ward_ir::ClassKind::Interface {
        scope.uses_typing = true;
        let mut bases: Vec<String> = c.interfaces.iter().map(|&i| scope.adt(i)).collect();
        bases.push("_typing.Protocol".to_owned());
        let _ = writeln!(out, "\n\nclass {name}({}):", bases.join(", "));
        if methods.is_empty() {
            out.push_str("    pass\n");
        }
        for f in methods {
            let py_name = body::method_name(f, options.asyncio);
            let _ = writeln!(out, "{}", method_stub(scope, top, f, options, &py_name));
        }
        return;
    }
    let base = c
        .base
        .map(|b| format!("({})", scope.adt(b)))
        .unwrap_or_default();
    let _ = writeln!(out, "\n\nclass {name}{base}:");
    let before = out.len();
    for f in &c.fields {
        let ann = scope.annotation(&f.ty, &[]);
        let _ = writeln!(out, "    {}: {ann}", names::attr(&f.name));
    }
    if options.asyncio && c.base.is_none() {
        let has_init = methods.iter().any(|f| f.method.is_some_and(|m| m.is_init));
        if stub {
            let _ = writeln!(
                out,
                "    @classmethod\n    async def _new(cls, *args: _typing.Any) -> _typing.Self: ..."
            );
        } else {
            out.push_str(
                "\n    @classmethod\n    async def _new(cls, *args):\n        self = cls.__new__(cls)\n        await self._init(*args)\n        return self\n",
            );
            if !has_init {
                out.push_str("\n    async def _init(self):\n        pass\n");
            }
        }
    }
    for f in methods {
        let py_name = body::method_name(f, options.asyncio);
        let trace = format!("{}.{}", c.name, f.name);
        if stub {
            if !f.is_pub && f.method.is_some_and(|m| !m.is_init) {
                continue;
            }
            let _ = writeln!(out, "{}", method_stub(scope, top, f, options, &py_name));
        } else if matches!(f.body, ward_ir::Body::Abstract) {
            let stub = method_stub(scope, top, f, options, &py_name);
            let head = stub.strip_suffix(" ...").unwrap_or(&stub);
            let _ = writeln!(
                out,
                "\n{head}\n        raise NotImplementedError({})",
                names::string(&trace)
            );
        } else {
            let at = out.len();
            emit_fn(out, scope, top, f, options, "    ", &py_name, &trace);
            // No blank line between `class X:` and its first member.
            if at == before && out[at..].starts_with('\n') {
                out.remove(at);
            }
        }
    }
    if out.len() == before {
        out.push_str("    pass\n");
    }
}

fn method_stub(
    scope: &mut Scope,
    top: &HashSet<String>,
    f: &ward_ir::Fn,
    options: Options,
    py_name: &str,
) -> String {
    let names: Vec<String> = {
        let g = FnGen::new(f, scope, top);
        f.params.iter().map(|&p| g.local(p).to_owned()).collect()
    };
    let params: Vec<String> = names
        .into_iter()
        .zip(&f.params)
        .zip(&f.trusted)
        .enumerate()
        .map(|(i, ((n, &p), &trusted))| {
            if i == 0 {
                return n;
            }
            let ann = scope.annotation(&f.locals[p].ty, &f.generics);
            if trusted {
                format!("{n}: _rt.Trusted[{ann}]")
            } else {
                format!("{n}: {ann}")
            }
        })
        .collect();
    let ret = scope.annotation(&f.ret, &f.generics);
    format!(
        "    {} {py_name}({}) -> {ret}: ...",
        def(options),
        params.join(", ")
    )
}

/// `\n    a,\n    b,\n` between brackets, or nothing when empty.
fn bracketed(lines: &[String]) -> String {
    if lines.is_empty() {
        String::new()
    } else {
        format!("\n{}\n", lines.join("\n"))
    }
}

fn record_class(out: &mut String, scope: &mut Scope, r: &Record, stub: bool) {
    let name = names::ident(&r.name);
    let generic = generic_base(&r.generics, stub);
    let _ = writeln!(
        out,
        "\n\n@_dc.dataclass(frozen=True)\nclass {name}{}:",
        generic.map_or_else(String::new, |g| format!("({g})"))
    );
    if r.fields.is_empty() {
        out.push_str("    pass\n");
    }
    for f in &r.fields {
        let ann = scope.annotation(&f.ty, &r.generics);
        let _ = writeln!(out, "    {}: {ann}", names::attr(&f.name));
    }
}

/// `_typing.Generic[_T]` for a generic class in a stub; runtime classes don't need it.
fn generic_base(generics: &[String], stub: bool) -> Option<String> {
    if !stub || generics.is_empty() {
        return None;
    }
    let vars: Vec<String> = generics.iter().map(|g| type_var(g)).collect();
    Some(format!("_typing.Generic[{}]", vars.join(", ")))
}

fn enum_classes(out: &mut String, scope: &mut Scope, e: &Enum, stub: bool) {
    let name = names::ident(&e.name);
    if e.is_unit_only() {
        let _ = writeln!(out, "\n\nclass {name}(_enum.Enum):");
        if e.variants.is_empty() {
            out.push_str("    pass\n");
        }
        for v in &e.variants {
            let _ = writeln!(
                out,
                "    {} = {}",
                names::attr(&v.name),
                names::string(&v.name)
            );
        }
        return;
    }
    let generic = generic_base(&e.generics, stub);
    let _ = writeln!(
        out,
        "\n\nclass {name}{}:",
        generic
            .as_ref()
            .map_or_else(String::new, |g| format!("({g})"))
    );
    if stub {
        for v in &e.variants {
            let _ = writeln!(
                out,
                "    {}: _typing.ClassVar[type[{}]]",
                names::attr(&v.name),
                names::variant_class(&e.name, &v.name)
            );
        }
    } else {
        out.push_str("    pass\n");
    }
    let base = if e.generics.is_empty() || !stub {
        name.clone()
    } else {
        let vars: Vec<String> = e.generics.iter().map(|g| type_var(g)).collect();
        format!("{name}[{}]", vars.join(", "))
    };
    for v in &e.variants {
        let _ = writeln!(
            out,
            "\n\n@_dc.dataclass(frozen=True)\nclass {}({base}):",
            names::variant_class(&e.name, &v.name)
        );
        if v.fields.is_empty() {
            out.push_str("    pass\n");
        }
        for (i, t) in v.fields.iter().enumerate() {
            let ann = scope.annotation(t, &e.generics);
            let _ = writeln!(out, "    _{i}: {ann}");
        }
    }
    if !stub {
        out.push_str("\n\n");
        for v in &e.variants {
            let _ = writeln!(
                out,
                "{name}.{} = {}",
                names::attr(&v.name),
                names::variant_class(&e.name, &v.name)
            );
        }
    }
}

fn stub(program: &Program, id: ModuleId, module: &Module, options: Options) -> String {
    let mut scope = Scope::new(program, Some(id));
    let mut body = String::new();
    for r in &module.records {
        record_class(&mut body, &mut scope, r, true);
    }
    for e in &module.enums {
        enum_classes(&mut body, &mut scope, e, true);
    }
    let top = top_level_names(program, module);
    for c in &module.classes {
        class(&mut body, &mut scope, &top, module, c, options, true);
    }
    for f in module.fns.iter().filter(|f| f.is_pub && f.method.is_none()) {
        let names: Vec<String> = {
            let g = FnGen::new(f, &mut scope, &top);
            f.params.iter().map(|&p| g.local(p).to_owned()).collect()
        };
        let params: Vec<String> = names
            .into_iter()
            .zip(&f.params)
            .zip(&f.trusted)
            .map(|((n, &p), &trusted)| {
                let ann = scope.annotation(&f.locals[p].ty, &f.generics);
                if trusted {
                    format!("{n}: _rt.Trusted[{ann}]")
                } else {
                    format!("{n}: {ann}")
                }
            })
            .collect();
        let ret = scope.annotation(&f.ret, &f.generics);
        let _ = write!(
            body,
            "\n\n{} {}({}) -> {ret}: ...\n",
            def(options),
            names::ident(&f.name),
            params.join(", ")
        );
    }

    let mut generics: Vec<&String> = module
        .records
        .iter()
        .flat_map(|r| &r.generics)
        .chain(module.enums.iter().flat_map(|e| &e.generics))
        .chain(
            module
                .fns
                .iter()
                .filter(|f| f.is_pub)
                .flat_map(|f| &f.generics),
        )
        .collect();
    generics.sort();
    generics.dedup();
    let needs_typing = scope.uses_typing
        || !generics.is_empty()
        || module.enums.iter().any(|e| !e.is_unit_only())
        || (options.asyncio && !module.classes.is_empty());

    let mut out = header(module);
    let mut imports = Vec::new();
    if !module.records.is_empty() || module.enums.iter().any(|e| !e.is_unit_only()) {
        imports.push("import dataclasses as _dc");
    }
    if module.enums.iter().any(Enum::is_unit_only) {
        imports.push("import enum as _enum");
    }
    if needs_typing {
        imports.push("import typing as _typing");
    }
    for line in &imports {
        let _ = writeln!(out, "{line}");
    }
    let module_imports = scope.import_lines();
    if !module_imports.is_empty() {
        out.push('\n');
    }
    for line in module_imports {
        let _ = writeln!(out, "{line}");
    }
    if !generics.is_empty() {
        out.push('\n');
    }
    for g in generics {
        let v = type_var(g);
        let _ = writeln!(out, "{v} = _typing.TypeVar({})", names::string(&v));
    }
    out.push_str(&body);
    out
}

/// A script that calls `function` from the entry module with JSON arguments (from
/// `argv`), and prints the result as JSON. Used by `ward run`.
pub struct Runner {
    pub script: String,
    pub arity: usize,
}

pub fn runner(program: &Program, function: &str) -> Option<Runner> {
    let entry = program.modules.first()?;
    let f = entry.fns.iter().find(|f| f.name == function)?;
    let mut scope = Scope::new(program, None);
    scope.imports.insert(ModuleId(0));
    let params: Vec<String> = f
        .params
        .iter()
        .map(|&p| scope.descriptor(&f.locals[p].ty))
        .collect();
    let target = scope.func(f.def);
    let trusted: Vec<&str> = f
        .trusted
        .iter()
        .map(|&t| if t { "True" } else { "False" })
        .collect();
    // Every model alias the program's `model {...}` clauses use.
    let mut aliases: Vec<&str> = program
        .modules
        .iter()
        .flat_map(|m| &m.fns)
        .filter_map(|f| f.model.as_ref())
        .flat_map(|p| p.models.iter().flatten())
        .map(String::as_str)
        .collect();
    aliases.sort_unstable();
    aliases.dedup();
    let aliases: Vec<String> = aliases.into_iter().map(names::string).collect();
    let mut script = String::from(RUNNER_PRELUDE);
    for line in scope.import_lines() {
        let _ = writeln!(script, "{line}");
    }
    let _ = write!(
        script,
        "\nsys.exit(main({}, {target}, [{}], [{}], [{}]))\n",
        names::string(function),
        params.join(", "),
        trusted.join(", "),
        aliases.join(", ")
    );
    Some(Runner {
        script,
        arity: f.params.len(),
    })
}

/// The script `ward test` runs: the entry module's tests, replayed from (or recorded
/// to) the recordings file. Settings come from the environment.
pub fn test_runner(program: &Program) -> Option<String> {
    let entry = program.modules.first()?;
    let mut aliases: Vec<&str> = program
        .modules
        .iter()
        .flat_map(|m| &m.fns)
        .filter_map(|f| f.model.as_ref())
        .flat_map(|p| p.models.iter().flatten())
        .map(String::as_str)
        .collect();
    aliases.sort_unstable();
    aliases.dedup();
    let mut sources: Vec<&str> = program
        .modules
        .iter()
        .flat_map(|m| &m.tools)
        .map(|t| t.source.as_str())
        .collect();
    sources.sort_unstable();
    sources.dedup();
    let list = |xs: Vec<&str>| {
        xs.into_iter()
            .map(names::string)
            .collect::<Vec<_>>()
            .join(", ")
    };
    Some(format!(
        "{TEST_RUNNER}\nimport {} as _module\n\nsys.exit(main(_module, [{}], [{}]))\n",
        entry.name,
        list(aliases),
        list(sources)
    ))
}

const TEST_RUNNER: &str = r#"import json
import os
import sys

from wardscript import runtime, testing
from wardscript.mock import MockModel


def main(module, aliases, sources):
    record = os.environ.get("WARD_RECORD") == "1"
    model, models, tools = None, {}, None
    if record:
        mock = os.environ.get("WARD_MOCK")
        specs = json.loads(os.environ.get("WARD_MODEL") or "{}")
        if mock:
            with open(mock, encoding="utf-8") as f:
                model = MockModel.from_json(f.read())
        else:
            from wardscript.providers import load

            try:
                loaded = {alias: load(spec) for alias, spec in specs.items()}
            except (ImportError, ValueError) as e:
                print(f"error: {e}", file=sys.stderr)
                return 2
            model = loaded.pop("", None)
            models = loaded
        config = os.environ.get("WARD_MCP_CONFIG")
        if config:
            from wardscript import mcp

            tools = mcp.load_config(config)
    ok = testing.run(
        getattr(module, "__ward_tests__", []),
        recordings=os.environ["WARD_RECORDINGS"],
        record=record,
        filters=json.loads(os.environ.get("WARD_FILTERS") or "[]"),
        aliases=aliases,
        sources=sources,
        model=model,
        models=models,
        tools=tools,
    )
    return 0 if ok else 4
"#;

const RUNNER_PRELUDE: &str = r#"import json
import os
import sys

from wardscript import DecodeError, Thrown, WardError, _rt, decode, encode, runtime
from wardscript.mock import MockModel


# Arguments on the command line come from whoever runs it, so they're vouched for.
def main(name, fn, params, trusted, aliases):
    mock = os.environ.get("WARD_MOCK")
    specs = json.loads(os.environ.get("WARD_MODEL") or "{}")
    mcp_config = os.environ.get("WARD_MCP_CONFIG")
    if mcp_config:
        from wardscript import mcp

        runtime.configure(tools=mcp.load_config(mcp_config))
    if mock:
        with open(mock, encoding="utf-8") as f:
            model = MockModel.from_json(f.read())
        # The mock answers for every alias.
        runtime.configure(model=model, models={a: model for a in aliases})
    elif specs:
        from wardscript.providers import load

        for alias in specs:
            if alias and alias not in aliases:
                print(f"error: no `model {{...}}` clause uses the alias `{alias}`", file=sys.stderr)
                return 2
        loaded = {}
        try:
            for alias in ["", *aliases]:
                spec = specs.get(alias) or specs.get("")
                if spec and spec not in loaded:
                    loaded[spec] = load(spec)
        except (ImportError, ValueError) as e:
            print(f"error: model `{spec}`: {e}", file=sys.stderr)
            return 2
        runtime.configure(
            model=loaded.get(specs.get("")),
            models={a: loaded[s] for a in aliases if (s := specs.get(a) or specs.get(""))},
        )
    try:
        return call(name, fn, params, trusted)
    finally:
        run = runtime.last_run()
        if run is not None and run.path is not None:
            print(f"trace: {run.id} (ward trace show {run.id})", file=sys.stderr)


def call(name, fn, params, trusted):
    args = []
    for i, (param, text) in enumerate(zip(params, sys.argv[1:])):
        try:
            arg = decode(param, json.loads(text), f"argument {i + 1}")
            args.append(_rt.Trusted(arg) if trusted[i] else arg)
        except json.JSONDecodeError as e:
            print(f"error: argument {i + 1} is not valid JSON: {e}", file=sys.stderr)
            return 2
        except DecodeError as e:
            print(f"error: invalid argument: {e}", file=sys.stderr)
            return 2
    try:
        result = fn(*args)
    except Thrown as e:
        print(f"error: `{name}` threw {json.dumps(encode(e.value))}", file=sys.stderr)
        return 3
    except WardError as e:
        print(f"error: {e}", file=sys.stderr)
        return 3
    print(json.dumps(encode(result), indent=2, ensure_ascii=False))
    return 0


"#;
