// The Wardscript runtime for TypeScript and JavaScript: what hosts use to configure
// and call modules generated by `ward build --target typescript`.
//
//   import { configure, MockModel } from "wardscript";
//   configure({ model: new MockModel({ triage: {...} }) });

export { type ApprovalRequest, type Approver, type Config, configure, reset } from "./config.ts";
export {
  AiOutputError,
  ApprovalDenied,
  BudgetExceeded,
  BudgetUnenforceable,
  DecodeError,
  ModelError,
  ModelUnavailable,
  NoModelError,
  PanicError,
  RateLimited,
  TestFailure,
  Thrown,
  ToolError,
  TrustError,
  WardError,
} from "./errors.ts";
export { type AiRequest, type Completion, type Model, instructions } from "./model.ts";
export { MockError, MockModel, Raw, Seq, Usage } from "./mock.ts";
export { Anthropic } from "./providers/anthropic.ts";
export { OpenAI } from "./providers/openai.ts";
export { Server as McpServer, loadConfig as loadMcpConfig } from "./mcp.ts";
export { decode, encode, jsonSchema } from "./schema.ts";
export { Trusted } from "./trust.ts";
export { Some, type Option } from "./values.ts";
export { last as lastRun, type Run } from "./audit.ts";
