[package]
name = "ward_cli"
description = "The `ward` command-line tool."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "ward"
path = "src/main.rs"

[dependencies]
clap.workspace = true
ward_syntax.workspace = true
ward_resolve.workspace = true
ward_check.workspace = true
ward_ir.workspace = true
ward_codegen_py.workspace = true
ward_codegen_ts.workspace = true
ward_runtime.workspace = true
ward_lsp.workspace = true
ariadne.workspace = true
serde_json.workspace = true
ureq.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
