//! WIR to TypeScript: one `.ts` module per Wardscript module, importing the `wardscript`
//! runtime package as `_rt`.
//!
//! Records become interfaces of readonly fields, used as plain objects. Enums whose
//! variants have no fields become unions of string literals; others become unions of
//! `{tag, _0, ...}` objects. Each record and enum also has a runtime description,
//! `Name$`, for decoding model answers. Every function is `async`.

mod body;
mod names;

use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::PathBuf;

use ward_ir::{Enum, Fn, Module, ModuleId, Program, Record, Ty};

use crate::body::FnGen;
use crate::names::{Scope, descriptor_name, ident};

pub struct OutputFile {
    /// Relative to the output directory: `support/tickets.ts`.
    pub path: PathBuf,
    pub contents: String,
}

pub fn generate(program: &Program) -> Vec<OutputFile> {
    program
        .modules
        .iter()
        .enumerate()
        .map(|(i, module)| {
            let base: PathBuf = module.name.split('.').collect();
            OutputFile {
                path: base.with_extension("ts"),
                contents: typescript(program, ModuleId(i as u32), module),
            }
        })
        .collect()
}

fn header(module: &Module) -> String {
    let file = std::path::Path::new(&module.path)
        .file_name()
        .map_or_else(|| module.path.clone(), |f| f.to_string_lossy().into_owned());
    format!("// Generated by `ward build --target typescript` from {file}. Do not edit.\n")
}

fn top_level_names(program: &Program, module: &Module) -> HashSet<String> {
    let mut out = HashSet::new();
    for r in &module.records {
        out.insert(ident(&r.name));
        out.insert(descriptor_name(&r.name));
    }
    for e in &module.enums {
        out.insert(ident(&e.name));
        out.insert(descriptor_name(&e.name));
    }
    for c in &module.classes {
        out.insert(ident(&c.name));
        out.insert(format!("{}$new", ident(&c.name)));
    }
    for f in module.fns.iter().filter(|f| f.method.is_none()) {
        out.insert(ident(&f.name));
    }
    for r in &module.refinements {
        out.insert(r.name.clone());
    }
    for m in &program.modules {
        out.insert(names::module_alias(&m.name));
    }
    out
}

fn generics(gs: &[String]) -> String {
    if gs.is_empty() {
        String::new()
    } else {
        format!("<{}>", gs.join(", "))
    }
}

fn record_decl(out: &mut String, scope: &mut Scope, r: &Record) {
    let fields: Vec<String> = r
        .fields
        .iter()
        .map(|f| {
            format!(
                "  readonly {}: {};",
                f.name,
                scope.annotation(&f.ty, &r.generics)
            )
        })
        .collect();
    let _ = writeln!(
        out,
        "\nexport interface {}{} {{\n{}\n}}",
        ident(&r.name),
        generics(&r.generics),
        fields.join("\n")
    );
}

fn enum_decl(out: &mut String, scope: &mut Scope, e: &Enum) {
    let variants: Vec<String> = e
        .variants
        .iter()
        .map(|v| {
            if e.is_unit_only() {
                names::string(&v.name)
            } else {
                let mut parts = vec![format!("readonly tag: {}", names::string(&v.name))];
                for (i, t) in v.fields.iter().enumerate() {
                    parts.push(format!(
                        "readonly _{i}: {}",
                        scope.annotation(t, &e.generics)
                    ));
                }
                format!("{{ {} }}", parts.join("; "))
            }
        })
        .collect();
    let body = if variants.is_empty() {
        "never".to_owned()
    } else {
        variants.join(" | ")
    };
    let _ = writeln!(
        out,
        "\nexport type {}{} = {body};",
        ident(&e.name),
        generics(&e.generics)
    );
}

fn function(out: &mut String, scope: &mut Scope, top: &HashSet<String>, f: &Fn) {
    let export = if f.is_pub { "export " } else { "" };
    let head = format!(
        "{export}async function {}{}",
        ident(&f.name),
        generics(&f.generics)
    );
    out.push('\n');
    traced(out, scope, top, f, "", &head, &f.name);
}

/// A function or method whose body runs inside its audit-trace run and budget. `pad`
/// is the indentation of the declaration.
fn traced(
    out: &mut String,
    scope: &mut Scope,
    top: &HashSet<String>,
    f: &Fn,
    pad: &str,
    head: &str,
    trace_name: &str,
) {
    let is_method = f.method.is_some();
    let (param_names, body_lines, decls) = {
        let mut g = FnGen::new(f, scope, top);
        g.indent = 2 + pad.len() / 2;
        let names: Vec<String> = f.params.iter().map(|&p| g.local(p).to_owned()).collect();
        g.body();
        let decls = g.declarations();
        (names, g.lines, decls)
    };
    let params: Vec<String> = param_names
        .iter()
        .zip(&f.params)
        .zip(&f.trusted)
        .skip(usize::from(is_method))
        .map(|((name, &p), &trusted)| {
            let ann = scope.annotation(&f.locals[p].ty, &f.generics);
            if trusted {
                format!("{name}: {ann} | _rt.Trusted<{ann}>")
            } else {
                format!("{name}: {ann}")
            }
        })
        .collect();
    let ret = if f.ret == Ty::Unit {
        "void".to_owned()
    } else {
        scope.annotation(&f.ret, &f.generics)
    };
    let _ = writeln!(out, "{pad}{head}({}): Promise<{ret}> {{", params.join(", "));
    if is_method {
        if let Some(this) = param_names.first() {
            let _ = writeln!(out, "{pad}  const {this} = this;");
        }
    }
    // The outermost call is a run in the audit trace.
    let args: Vec<String> = param_names
        .iter()
        .zip(&f.params)
        .skip(usize::from(is_method))
        .map(|(n, &p)| format!("[{}, {n}]", names::string(&f.locals[p].name)))
        .collect();
    let mut open = format!(
        "{pad}  return _rt.call({}, [{}], ",
        names::string(trace_name),
        args.join(", ")
    );
    let mut close = String::from(");");
    if !f.budget.is_empty() {
        let limits: Vec<String> = f
            .budget
            .iter()
            .map(|(k, v)| match v {
                ward_ir::BudgetValue::Int(n) => format!("{k}: {n}"),
                ward_ir::BudgetValue::Float(x) => format!("{k}: {x:?}"),
            })
            .collect();
        let _ = write!(
            open,
            "() => _rt.budget({}, {{ {} }}, ",
            names::string(trace_name),
            limits.join(", ")
        );
        close.insert(0, ')');
    }
    let _ = writeln!(out, "{open}async () => {{");
    for d in decls {
        let _ = writeln!(out, "{pad}    {d}");
    }
    for line in body_lines {
        let _ = writeln!(out, "{line}");
    }
    let _ = writeln!(out, "{pad}  }}{close}\n{pad}}}");
}

/// The `init` constructing `class` runs: its own or the nearest base's.
pub(crate) fn init_of(program: &Program, class: ward_ir::DefId) -> Option<ward_ir::DefId> {
    let mut cur = Some(class);
    while let Some(c) = cur.and_then(|d| program.class(d)) {
        let own = c.methods.iter().copied().find(|&m| {
            program
                .func(m)
                .is_some_and(|f| f.method.is_some_and(|mo| mo.is_init))
        });
        if own.is_some() {
            return own;
        }
        cur = c.base;
    }
    None
}

/// A method's name in TypeScript. Each class's `init` has its own name, so a subclass's
/// can take different parameters.
pub(crate) fn method_name(program: &Program, f: &Fn) -> String {
    match f.method {
        Some(m) if m.is_init => format!("_init${}", ident(program.adt_name(m.class))),
        _ if f.name == "constructor" => "constructor_".to_owned(),
        _ => f.name.clone(),
    }
}

/// `name(params): Promise<T>`, for an interface or an abstract method.
fn signature(scope: &mut Scope, program: &Program, f: &Fn) -> String {
    let params: Vec<String> = f
        .params
        .iter()
        .zip(&f.trusted)
        .skip(1)
        .map(|(&p, &trusted)| {
            let ann = scope.annotation(&f.locals[p].ty, &[]);
            let ann = if trusted {
                format!("{ann} | _rt.Trusted<{ann}>")
            } else {
                ann
            };
            format!("{}: {ann}", ident(&f.locals[p].name))
        })
        .collect();
    let ret = if f.ret == Ty::Unit {
        "void".to_owned()
    } else {
        scope.annotation(&f.ret, &[])
    };
    format!(
        "{}({}): Promise<{ret}>",
        method_name(program, f),
        params.join(", ")
    )
}

/// A class, and `Name$new`, which creates an object and awaits its `init`: a
/// constructor can't be async.
fn class_decl(
    out: &mut String,
    scope: &mut Scope,
    top: &HashSet<String>,
    module: &Module,
    c: &ward_ir::Class,
) {
    let program = scope.program;
    let name = ident(&c.name);
    let export = if c.is_pub { "export " } else { "" };
    let interfaces: Vec<String> = c.interfaces.iter().map(|&i| scope.adt(i)).collect();
    let methods: Vec<&Fn> = c
        .methods
        .iter()
        .filter_map(|&d| module.fns.iter().find(|f| f.def == d))
        .collect();
    if c.kind == ward_ir::ClassKind::Interface {
        let extends = if interfaces.is_empty() {
            String::new()
        } else {
            format!(" extends {}", interfaces.join(", "))
        };
        let _ = writeln!(out, "\n{export}interface {name}{extends} {{");
        for f in methods {
            let _ = writeln!(out, "  {};", signature(scope, program, f));
        }
        let _ = writeln!(out, "}}");
        return;
    }
    let mut head = String::new();
    if let Some(b) = c.base {
        let _ = write!(head, " extends {}", scope.adt(b));
    }
    if !interfaces.is_empty() {
        let _ = write!(head, " implements {}", interfaces.join(", "));
    }
    let is_abstract = c.kind == ward_ir::ClassKind::Abstract;
    let abstract_kw = if is_abstract { "abstract " } else { "" };
    let _ = writeln!(out, "\n{export}{abstract_kw}class {name}{head} {{");
    for f in &c.fields {
        let _ = writeln!(out, "  {}!: {};", f.name, scope.annotation(&f.ty, &[]));
    }
    for f in methods {
        if matches!(f.body, ward_ir::Body::Abstract) {
            let _ = writeln!(out, "  abstract {};", signature(scope, program, f));
            continue;
        }
        let head = format!("async {}", method_name(program, f));
        let trace = format!("{}.{}", c.name, f.name);
        traced(out, scope, top, f, "  ", &head, &trace);
    }
    let _ = writeln!(out, "}}");
    if is_abstract {
        return;
    }
    let init = init_of(program, c.def).and_then(|d| program.func(d));
    let params: Vec<(String, String)> = init
        .map(|f| {
            f.params
                .iter()
                .zip(&f.trusted)
                .skip(1)
                .map(|(&p, &trusted)| {
                    let ann = scope.annotation(&f.locals[p].ty, &[]);
                    let ann = if trusted {
                        format!("{ann} | _rt.Trusted<{ann}>")
                    } else {
                        ann
                    };
                    (ident(&f.locals[p].name), ann)
                })
                .collect()
        })
        .unwrap_or_default();
    let decl: Vec<String> = params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
    let args: Vec<&str> = params.iter().map(|(n, _)| n.as_str()).collect();
    let _ = writeln!(
        out,
        "\n{export}async function {name}$new({}): Promise<{name}> {{\n  const self = new {name}();",
        decl.join(", ")
    );
    if let Some(f) = init {
        let _ = writeln!(
            out,
            "  await self.{}({});",
            method_name(program, f),
            args.join(", ")
        );
    }
    let _ = writeln!(out, "  return self;\n}}");
}

fn typescript(program: &Program, id: ModuleId, module: &Module) -> String {
    let mut scope = Scope::new(program, id);
    let mut body = String::new();
    let top = top_level_names(program, module);

    for r in &module.records {
        record_decl(&mut body, &mut scope, r);
    }
    for e in &module.enums {
        enum_decl(&mut body, &mut scope, e);
    }
    // Runtime descriptions; their fields are thunks, so order doesn't matter.
    for r in &module.records {
        let fields: Vec<String> = r
            .fields
            .iter()
            .map(|f| format!("[{}, {}]", names::string(&f.name), scope.descriptor(&f.ty)))
            .collect();
        let _ = writeln!(
            body,
            "\nexport const {} = _rt.record({}, () => [{}]);",
            descriptor_name(&r.name),
            names::string(&r.name),
            fields.join(", ")
        );
    }
    for e in &module.enums {
        let variants: Vec<String> = e
            .variants
            .iter()
            .map(|v| {
                let fields: Vec<String> = v.fields.iter().map(|t| scope.descriptor(t)).collect();
                format!("[{}, [{}]]", names::string(&v.name), fields.join(", "))
            })
            .collect();
        let _ = writeln!(
            body,
            "\nexport const {} = _rt.enum_({}, () => [{}]);",
            descriptor_name(&e.name),
            names::string(&e.name),
            variants.join(", ")
        );
    }
    for c in &module.classes {
        class_decl(&mut body, &mut scope, &top, module, c);
    }
    for f in module.fns.iter().filter(|f| f.method.is_none()) {
        function(&mut body, &mut scope, &top, f);
    }
    // Refinements: plain functions of `it`, outside the audit trace.
    for r in &module.refinements {
        let f = &r.func;
        let (param, lines, decls) = {
            let mut g = FnGen::new(f, &mut scope, &top);
            g.asyncio = false;
            g.body();
            let decls = g.declarations();
            (g.local(f.params[0]).to_owned(), g.lines, decls)
        };
        let ty = scope.annotation(&f.locals[f.params[0]].ty, &[]);
        let _ = writeln!(body, "\nfunction {}({param}: {ty}): boolean {{", r.name);
        for d in decls {
            let _ = writeln!(body, "  {d}");
        }
        for line in lines {
            let _ = writeln!(body, "{line}");
        }
        let _ = writeln!(body, "}}");
    }

    let mut out = header(module);
    out.push_str("import * as _rt from \"wardscript/rt\";\n");
    for line in scope.import_lines() {
        let _ = writeln!(out, "{line}");
    }
    out.push_str(&body);
    out
}
