[package]
name = "ws_cli"
description = "The `ward` command-line tool."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "ward"
path = "src/main.rs"

[dependencies]
clap.workspace = true
ws_syntax.workspace = true
ws_resolve.workspace = true
ws_check.workspace = true
ws_ir.workspace = true
ws_codegen_py.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
